SELECT DISTINCT ?route ?sensor ?swP ?sw
WHERE
{
	?route base:follows ?swP .
	?swP base:switch ?sw .
	?sw base:sensor ?sensor .

	?route rdf:type base:Route .
	?swP rdf:type base:SwitchPosition .
	?sw rdf:type base:Switch .
	?sensor rdf:type base:Sensor .

	OPTIONAL {
		?route ?xDefinedBy ?sensor .
		FILTER (sameTerm(base:definedBy, ?xDefinedBy))
	} .
	FILTER (!bound(?xDefinedBy))
}
